version: '3'
services:
  proxy:
    image: nginx
    volumes:
       - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
       - /etc/letsencrypt:/etc/letsencrypt # 餈質
      #  - ./Dockerfile:/etc # 餈質

    ports:
      - "443:443"
      - "3335:3335"
  app:
    build:
      context: .
    tty: true
    volumes:
      - ./tango:/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "[ -f ~/.exec-once ] || { yarn install && touch ~/.exec-once; } && yarn dev"
    ports:
      - "3333:3000"
  mysql:
    image: mysql:latest
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/my.conf:/etc/mysql/conf.d/my.cnf
      - db_data:/var/lib/mysql

  trans:
    build: ./python
    ports:
      - "5001:5001"
    volumes:
      - "./trans:/usr/src/app"
    environment:
      - FLASK_DEBUG=1
    tty: true
    command: python app.py

volumes:
  db_data:

